services:
  picare-oms-client:
    
    image: ghcr.io/tritruong666/picare-oms-client:latest
    container_name: picare-oms-client
    restart: always
    networks:
      - picare-network
      - web_network

networks:
  picare-network:
    external: true
  web_network: 
    external: true
    